answer = int(input("Give a whole number that is less than 5.\n"))
print(answer < 5)
answer = int(input("Give a whole number that is less than 10.\n"))
print(answer < 10)
answer = int(input("Give a whole number that is less than 8.\n"))
print(answer < 8)
answer = int(input("Give a whole number that is less than 24.\n"))
print(answer < 24)
answer = int(input("Give a whole number that is less than 100.\n"))
print(answer < 100)